version: '3'
services:
  kafka: 
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 192.168.235.10:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.235.10:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1